/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CapAuth {}
  interface CapAuthAttributes extends StencilHTMLAttributes {}

  interface CapPassword {
    'label': string;
    'showPassword': boolean;
  }
  interface CapPasswordAttributes extends StencilHTMLAttributes {
    'label'?: string;
    'showPassword'?: boolean;
  }

  interface CapPesel {
    'label': string;
  }
  interface CapPeselAttributes extends StencilHTMLAttributes {
    'label'?: string;
  }

  interface UcSpinner {}
  interface UcSpinnerAttributes extends StencilHTMLAttributes {}

  interface UcStockFinder {}
  interface UcStockFinderAttributes extends StencilHTMLAttributes {
    'onUcSymbolSelected'?: (event: CustomEvent<string>) => void;
  }

  interface UcStockPrice {
    'stockSymbol': string;
  }
  interface UcStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CapAuth': Components.CapAuth;
    'CapPassword': Components.CapPassword;
    'CapPesel': Components.CapPesel;
    'UcSpinner': Components.UcSpinner;
    'UcStockFinder': Components.UcStockFinder;
    'UcStockPrice': Components.UcStockPrice;
  }

  interface StencilIntrinsicElements {
    'cap-auth': Components.CapAuthAttributes;
    'cap-password': Components.CapPasswordAttributes;
    'cap-pesel': Components.CapPeselAttributes;
    'uc-spinner': Components.UcSpinnerAttributes;
    'uc-stock-finder': Components.UcStockFinderAttributes;
    'uc-stock-price': Components.UcStockPriceAttributes;
  }


  interface HTMLCapAuthElement extends Components.CapAuth, HTMLStencilElement {}
  var HTMLCapAuthElement: {
    prototype: HTMLCapAuthElement;
    new (): HTMLCapAuthElement;
  };

  interface HTMLCapPasswordElement extends Components.CapPassword, HTMLStencilElement {}
  var HTMLCapPasswordElement: {
    prototype: HTMLCapPasswordElement;
    new (): HTMLCapPasswordElement;
  };

  interface HTMLCapPeselElement extends Components.CapPesel, HTMLStencilElement {}
  var HTMLCapPeselElement: {
    prototype: HTMLCapPeselElement;
    new (): HTMLCapPeselElement;
  };

  interface HTMLUcSpinnerElement extends Components.UcSpinner, HTMLStencilElement {}
  var HTMLUcSpinnerElement: {
    prototype: HTMLUcSpinnerElement;
    new (): HTMLUcSpinnerElement;
  };

  interface HTMLUcStockFinderElement extends Components.UcStockFinder, HTMLStencilElement {}
  var HTMLUcStockFinderElement: {
    prototype: HTMLUcStockFinderElement;
    new (): HTMLUcStockFinderElement;
  };

  interface HTMLUcStockPriceElement extends Components.UcStockPrice, HTMLStencilElement {}
  var HTMLUcStockPriceElement: {
    prototype: HTMLUcStockPriceElement;
    new (): HTMLUcStockPriceElement;
  };

  interface HTMLElementTagNameMap {
    'cap-auth': HTMLCapAuthElement
    'cap-password': HTMLCapPasswordElement
    'cap-pesel': HTMLCapPeselElement
    'uc-spinner': HTMLUcSpinnerElement
    'uc-stock-finder': HTMLUcStockFinderElement
    'uc-stock-price': HTMLUcStockPriceElement
  }

  interface ElementTagNameMap {
    'cap-auth': HTMLCapAuthElement;
    'cap-password': HTMLCapPasswordElement;
    'cap-pesel': HTMLCapPeselElement;
    'uc-spinner': HTMLUcSpinnerElement;
    'uc-stock-finder': HTMLUcStockFinderElement;
    'uc-stock-price': HTMLUcStockPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
