/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CapAuth {}
  interface CapButton {
    'color': "primary" | "secondary";
    'type': "submit" | "reset" | "button";
  }
  interface CapEmail {
    'isValid': boolean;
    'placeholder': string;
    'validate': () => Promise<boolean>;
    'value': string;
  }
  interface CapPassword {
    'isValid': boolean;
    'pattern': string;
    'placeholder': string;
    'showPassword': boolean;
    'validate': () => Promise<boolean>;
    'value': string;
  }
  interface CapPesel {
    'isValid': boolean;
    'placeholder': string;
    'validate': () => Promise<boolean>;
    'value': string;
  }
  interface CapPushButton {
    'on': boolean;
  }
}

declare global {


  interface HTMLCapAuthElement extends Components.CapAuth, HTMLStencilElement {}
  var HTMLCapAuthElement: {
    prototype: HTMLCapAuthElement;
    new (): HTMLCapAuthElement;
  };

  interface HTMLCapButtonElement extends Components.CapButton, HTMLStencilElement {}
  var HTMLCapButtonElement: {
    prototype: HTMLCapButtonElement;
    new (): HTMLCapButtonElement;
  };

  interface HTMLCapEmailElement extends Components.CapEmail, HTMLStencilElement {}
  var HTMLCapEmailElement: {
    prototype: HTMLCapEmailElement;
    new (): HTMLCapEmailElement;
  };

  interface HTMLCapPasswordElement extends Components.CapPassword, HTMLStencilElement {}
  var HTMLCapPasswordElement: {
    prototype: HTMLCapPasswordElement;
    new (): HTMLCapPasswordElement;
  };

  interface HTMLCapPeselElement extends Components.CapPesel, HTMLStencilElement {}
  var HTMLCapPeselElement: {
    prototype: HTMLCapPeselElement;
    new (): HTMLCapPeselElement;
  };

  interface HTMLCapPushButtonElement extends Components.CapPushButton, HTMLStencilElement {}
  var HTMLCapPushButtonElement: {
    prototype: HTMLCapPushButtonElement;
    new (): HTMLCapPushButtonElement;
  };
  interface HTMLElementTagNameMap {
    'cap-auth': HTMLCapAuthElement;
    'cap-button': HTMLCapButtonElement;
    'cap-email': HTMLCapEmailElement;
    'cap-password': HTMLCapPasswordElement;
    'cap-pesel': HTMLCapPeselElement;
    'cap-push-button': HTMLCapPushButtonElement;
  }
}

declare namespace LocalJSX {
  interface CapAuth {}
  interface CapButton {
    'color'?: "primary" | "secondary";
    'onCustomClick'?: (event: CustomEvent<any>) => void;
    'type'?: "submit" | "reset" | "button";
  }
  interface CapEmail {
    'isValid'?: boolean;
    'onInputValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'value'?: string;
  }
  interface CapPassword {
    'isValid'?: boolean;
    'onInputValueChange'?: (event: CustomEvent<any>) => void;
    'pattern'?: string;
    'placeholder'?: string;
    'showPassword'?: boolean;
    'value'?: string;
  }
  interface CapPesel {
    'isValid'?: boolean;
    'onInputValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'value'?: string;
  }
  interface CapPushButton {
    'on'?: boolean;
    'onPushButtonStateChange'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'cap-auth': CapAuth;
    'cap-button': CapButton;
    'cap-email': CapEmail;
    'cap-password': CapPassword;
    'cap-pesel': CapPesel;
    'cap-push-button': CapPushButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'cap-auth': LocalJSX.CapAuth & JSXBase.HTMLAttributes<HTMLCapAuthElement>;
      'cap-button': LocalJSX.CapButton & JSXBase.HTMLAttributes<HTMLCapButtonElement>;
      'cap-email': LocalJSX.CapEmail & JSXBase.HTMLAttributes<HTMLCapEmailElement>;
      'cap-password': LocalJSX.CapPassword & JSXBase.HTMLAttributes<HTMLCapPasswordElement>;
      'cap-pesel': LocalJSX.CapPesel & JSXBase.HTMLAttributes<HTMLCapPeselElement>;
      'cap-push-button': LocalJSX.CapPushButton & JSXBase.HTMLAttributes<HTMLCapPushButtonElement>;
    }
  }
}


